CREATE COLUMN TABLE "CDL_SCH_LOGGING"."CDL_GL_ACK"("SAP_DOCUMENT" VARCHAR(10), "FISCAL_YEAR" VARCHAR(4), "COMPANY_CODE" VARCHAR(4), "REFERENCE_DOCUMENT" VARCHAR(16), "STATUS" VARCHAR(10), "COUNT" INTEGER, "ENTRY_DATE" DATE, PRIMARY KEY ("SAP_DOCUMENT", "FISCAL_YEAR", "COMPANY_CODE"),
FOREIGN KEY("SAP_DOCUMENT", "FISCAL_YEAR", "COMPANY_CODE") 
REFERENCES "CDL_SCH_LOGGING"."CDL_GL_HEADER" ("SAP_DOCUMENT", "FISCAL_YEAR", "COMPANY_CODE")
);